#!/bin/bash

#OPEN /etc/mysql/my.cnf
#ADD
#[mysql]
#user=root
#password=xyzw

mysql <<EOF

CREATE DATABASE IF NOT EXISTS BackupRestore;
USE BackupRestore;
CREATE TABLE IF NOT EXISTS Disks(	
			DISKID VARCHAR(10) , 
			USERNAME VARCHAR(50) , 
			IP VARCHAR(20) , 
			AVAILABLE_SPACE BIGINT , 
			PRIMARY KEY(DISKID) 
);

CREATE TABLE IF NOT EXISTS Storage(	
			CLIENTID VARCHAR(10) , 
			PATH VARCHAR(200) , 
			DISKID VARCHAR(20) ,
			PRIMARY KEY(CLIENTID,PATH,DISKID) 
);

CREATE TABLE IF NOT EXISTS Users(	
			CLIENTID VARCHAR(10) , 
			PASSWORD VARCHAR(2000) , 
			PRIMARY KEY(CLIENTID) 
);

CREATE TABLE IF NOT EXISTS DisksInfo(	
			DISKID VARCHAR(10) , 
			PASSWORD VARCHAR(2000) , 
			PRIMARY KEY(DISKID) 
);

EOF